package com.training.other;

public class ExceptionTest2 {

	public static void main(String[] args) throws Exception{
		
			String s="abc";
			int c= Integer.parseInt(s);
			int a = 10 / 0;
			System.out.println("im in try block2");	
		

	}
}
